server:
  port: 80

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show_sql: true

spring:
  datasource:
    url: jdbc:h2:mem:babplus
    driver-class-name: org.h2.Driver
    username: admin
    password: "!fhqht90"
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
  h2:
    console:
      enabled: true
      path: /h2-console