@user = Bearer eyJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiYWRtaW4ifV0sInVzZXJuYW1lIjoid25zdGtkZGw5MCIsImlhdCI6MTc1NDM3NjQ2NCwiZXhwIjoxNzkwMzc2NDY0fQ.hv3jE18ENGNGDfn1A5_nH5TdNsBw1UfG495LINCQF1p119IICSTFq2jGKPdGysTVKoe4F_Hxr9xHRhmKrW78ng


GET http://localhost:8082/
Content-Type: application/json

###
POST http://localhost:8082/auth/login
Content-Type: application/json

{
  "id": "wnstkddl90",
  "password": "Vlzkcb_!@12"
}


###
POST http://localhost:8082/users/join
Content-Type: application/json

{
  "id": "wnstkddl90d",
  "name": "조준상",
  "password": "Vlzkcb_!@12"
}

###
GET http://localhost:8082/stores
Content-Type: application/json
Authorization: {{user}}}

###
GET http://localhost:8082/stores/2
Content-Type: application/json
Authorization: {{user}}}

###
POST http://localhost:8082/stores
Content-Type: application/json
Authorization: {{user}}}

{
  "name": "상봉지점",
  "address": "중랑구 상봉동",
  "hotline": "02-3491-3433"
}

###
PATCH http://localhost:8082/stores/1
Content-Type: application/json
Authorization: {{user}}}

{
  "name": "상봉",
  "address": "중랑구",
  "hotline": "02-3491-3431",
  "enable": true
}


###
GET http://localhost:8082/stores/1/menus/1
Content-Type: application/json
Authorization: {{user}}}

###
POST http://localhost:8082/stores/2/menus
Content-Type: application/json
Authorization: {{user}}}

{
  "menuDate": "2025-08-27",
  "mealType": "BREAKFAST",
  "menuItemNames": [
    "깍두기",
    "소고기무국",
    "계란장조림",
    "멸치볶음",
    "오징어젓갈"
  ]

}

###
PATCH http://localhost:8082/stores/1/menus/1
Content-Type: application/json
Authorization: {{user}}}

{
  "menuDate": "2025-08-28",
  "mealType": "LUNCH",
  "menuItemNames": [
    "배추김치",
    "육계장",
    "불고기",
    "고등어조림",
    "어묵볶음"
  ]
}